 # Copyright (c) 2022, Qi Zhangyang.
 # All rights reserved.


datasets:
  objaverse_caption_tune: # name of the dataset builder
    dataset_card: dataset_card/objaverse_caption.md
    # data_dir: ${env.data_dir}/datasets
    # data_type: images # [images|videos|features]
    data_type: [images, points]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: https://storage.googleapis.com//datasets/coco_karpathy_train.json
          md5: aa31ac474cf6250ebb81d18348a07ed8
          storage: shapenet/lavis_annotations/shapenet_train.json
        val:
          url: https://storage.googleapis.com/datasets/coco_karpathy_val.json
          md5: b273847456ef5580e33713b1f7de52a0
          storage:  shapenet/lavis_annotations/shapenet_train.json
        test:
          url: https://storage.googleapis.com/datasets/coco_karpathy_test.json
          md5: 3ff34b0ef2db02d01c37399f6a2a6cd1
          storage: shapenet/lavis_annotations/shapenet_train.json
      images:
        storage: objaverse/images/
      points:
        storage: objaverse/points/
